apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: “true”
spec:
  rules:
  - host: test.columbusecosystem.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-service
          servicePort: 8080
  tls:
  - secretName: tls-staging-cert
    hosts:
    - test.columbusecosystem.com
